import { useState, useEffect } from 'react'

import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'

const IMAGE_DEFAULT = "https://picsum.photos/seed/random/200/300"

export default function Home() {
  const [pageData, setPageData] = useState({})

  useEffect(() => {
    let controller = new AbortController();

    fetch('https://628979125da6ddfd5d586fdd.mockapi.io/description', {
      signal: controller.signal
    })
      .then(res => res.json())
      .then(data => setPageData(data[0]))
  }, [])

  const URL_IMAGE = (pageData?.image || IMAGE_DEFAULT).replace('random', Date.now())

  return (
    <div>
      <Head>
        <title>{ pageData?.title || 'Titulo de Prueba' }</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='wrapper-image'>
        <Image layout='fill' src={`${ URL_IMAGE }?v1-${Date.now().toString()}`} alt="Imagen de Prueba"></Image>
      </div>

      <h1>{ pageData?.title || 'Titulo de Prueba' }</h1>

      <Link href="/products">Products</Link>
      <Link href="/admin">Admin</Link>

      <style global jsx>{`
        .wrapper-image {
          position: relative;
          width: 500px;
          min-height: 300px;
          height: auto;
        }

        .wrapper-image img {
          object-fit: cover;
        }
    `}</style>
    </div>
  )
}
